# Sevalet Configuration

# Server settings
server:
  host: "127.0.0.1"  # Listen on all interfaces
  port: 8080         # Port to listen on

# Path to command definition file
commands_file: "configs/commands.yaml"

# Default timeout (seconds)
default_timeout: 10
