# Allowed commands definition
commands:
  - name: ls
    description: "List directory contents"
    allowed_args:
      - "-l"
      - "-a"
      - "-h"
      - "-la"
      - "/tmp"
      - "/var/log"
      - "/etc"

  - name: cat
    description: "Display file contents"
    allowed_args:
      - "/var/log/syslog"
      - "/etc/hostname"
      - "/etc/os-release"

  - name: echo
    description: "Display text"
    allowed_args:
      - "hello"
      - "world"
      - "test"

  - name: date
    description: "Show current date and time"
    allowed_args:
      - "+%Y-%m-%d"
      - "+%H:%M:%S"
      - "--utc"

  - name: uptime
    description: "Show system uptime"
    allowed_args: []
